
version: v2.0
 
name: demo
 
on:
  push:
    branches:
      - master
      - release/*
      - main
    paths:
      - src/*
  tag:
    tags:
      - release_*
    from-branches:
      - master
  mr:
    target-branches:
      - master
    paths:
      - src/*/*
  
variables:
  DEPLOY_TYPE: dev
  APPROVE: xxx
  GIT_USERNAME:
    value: user1
    readonly: true
 
stages:
- name: "stage1"
  jobs:
    job_id_1:
      name: my_job_1
      steps:
      - run: |
          echo "stage1, job_id_1"
          echo "APPROVE is ${{ variables.APPROVE }}"
          echo ::set-variable name=APPROVE::yyy
          echo ::set-output name=a::111
          echo "hello world!" >> test.txt
        id: step_1
      - uses: UploadArtifactory@1.*
        with:
          filePath: test.txt
    job_id_2:
      name: my_job_2
      steps:
      - run: |
          echo "stage1, job_id_2"
- name: "stage2"
  jobs:
    job_id_2:
      name: my_job_3
      steps:
      - run: |
          echo "stage2, job_id_3"
          echo "APPROVE is ${{ variables.APPROVE }}"
          echo "steps.step_1.outputs.a is ${{ steps.step_1.outputs.a }}"